### ISSUE TITLE
Not sure if this is Intentional BUT

### ISSUE THREAD

**Issue by Soap2953** [Sunfished/Pokemmon#4]
A game was started with this mod being one of them. We had beaten the eye of cthulhu and unlocked the professor. The wiki says the evolution machine is unlocked post-eye of cthulhu, however it was not being sold. So i checked the code for this to see which boss he does sell it at. The comment above it says //after skeletron (which by the way is downedboss3) however, it says downedboss2 which is Brain of Cthulhu/Eater of Worlds. Is it supposed to be Eow/Boc or skeletron because that is kind of confusing

**Comment by Soap2953** [comment]
(by the way, did not mean to fork this, I barely know github anymore)

**Comment by Sunfished** [comment]
hey there! thanks for the issue.

this is ENTIRELY my fault, I've made some mistakes and messed up some areas of when the professor is meant to spawn and when he's supposed to sell the evolution machine. The wiki's info is incorrect. He will sell it after brain/worm is defeated.

An update I'm planning to push around tomorrow will change this however, so this information will be outdated. New version will have him spawn after king slime, and sells the evolution machine after eye.

**Comment by Sunfished** [comment]
I lied, machine is now after worm/brain. Closing this though!
