### ISSUE TITLE
Pokebox Bug

### ISSUE THREAD

**Issue by AptGetGnome** [Sunfished/Pokemmon#7]
Updated to the latest version of the mod, and the professor spawned, he sold a pokebox for 35 gold that apparently gives 1 stage 1 pokemon, i open it and all of a sudden he drops nearlly 6 inventorys worth of pokeballs, tested this glitch a few times, sometimes he gives only half an inventory, sometimes a full inventory, and sometimes a fair few number that it took multiple trips to pick them all up.
![image](https://user-images.githubusercontent.com/12438639/108622091-a22b7d00-748a-11eb-8934-ccc71c7a65f4.png)

**Comment by AptGetGnome** [comment]
I ended up running out of space in my Magic Storage system because of all of them
![image](https://user-images.githubusercontent.com/12438639/108622199-47465580-748b-11eb-823b-a17ef15f27ae.png)

**Comment by Sunfished** [comment]
HOW DID I MISS THIS.

thank you so much for catching this bug! I'll fix it in the next few hours

**Comment by AptGetGnome** [comment]
No worries! thought i should let you know because i wanted to catch em all legit ;) (though i guess its more, buy em all lol)

**Comment by Sunfished** [comment]
Fixed! thanks again for ur help!
