### ISSUE TITLE
Starter

### ISSUE THREAD

**Issue by Kimit10** [Sunfished/Pokemmon#8]

**Comment by Sunfished** [comment]
hey there! my email said you found a bug regarding pokeboxes not opening, but the description here must have been deleted.

did you still have the problem?

**Comment by Kimit10** [comment]
Hi, sorry for the late reply. It ended up not being a bug, just me not
realizing that I had to right click in the inventory to open the pokebox.
Thanks for responding anyways! I'm really enjoying the mod!

**Comment by Sunfished** [comment]
I see, no issue then! Glad ur enjoying the mod :)
